apiVersion: v1
kind: ServiceAccount
metadata:
  name: fogluted-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-nodes
subjects:
  - kind: ServiceAccount
    name: fogluted-service-account
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fogluted-deployment
  labels:
    app: fogluted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fogluted
  template:
    metadata:
      labels:
        app: fogluted
    spec:
      serviceAccountName: fogluted-service-account
      containers:
        - name: fogluted
          image: aliut/fogluted
          imagePullPolicy: Never