apiVersion: v1
kind: ServiceAccount
metadata:
  name: foglute-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-nodes
subjects:
  - kind: ServiceAccount
    name: foglute-service-account
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foglute-deployment
  labels:
    app: foglute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foglute
  template:
    metadata:
      labels:
        app: foglute
    spec:
      serviceAccountName: foglute-service-account
      containers:
        - name: foglute
          image: aliut/foglute
          imagePullPolicy: Never